name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Ensure this matches your build command

      - name: Deploy to Firebase
        id: firebase_deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: e-com-ci-cd  # Replace with your actual Firebase Project ID

      # Notify Discord on Successful Deployment
      - name: Notify Discord on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "**✅ Deployment Successful!**\n🌍 Live at: https://e-com-ci-cd.web.app/"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      # Notify Discord on Failed Deployment
      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "**❌ Deployment Failed!**\nCheck GitHub Actions logs for details."}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
